dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "pierciro"
    token:
      secure: "13e4fdec944e94ee1d8fb7e6f0acc8995d5882d5"

script:
- ant build
- sonar-scanner -Dsonar.login="13e4fdec944e94ee1d8fb7e6f0acc8995d5882d5"